
title: RSCC-2021 | Coronavirus Campaign
description: RSCC school blog campaign.
author: David Austin
enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/rscc-2021"

urls:
    - text: About Us
      url: /about/
    - text: Contact Us
      url: /Contact/
    - text: Blog
      url: /blog/
# url: "http://localhost:4000"
url: "https://ariestropixdev.github.io/rscc-2021"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blogs/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
